# Generated by Django 5.2.1 on 2025-06-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('event_type', models.CharField(choices=[('theatre', 'Театр'), ('concert', 'Концерт')], max_length=20)),
                ('source_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
