# Generated by Django 5.2.1 on 2025-05-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='addres',
            field=models.JSONField(blank=True, default=dict, verbose_name='Адрес'),
        ),
    ]
